Update yaml command

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -34,5 +34,14 @@ jobs:
 
       - name: Run Cypress
         run: |
-          export CYPRESS_BASE_URL=$(node .github/workflows/scripts/wait-for-netlify-deploy.js | grep -o 'Deploy URL: https://[^ ]*' | awk '{print $3}')
-          yarn test:cypress:ci 
+              output=$(node .github/workflows/scripts/wait-for-netlify-deploy.js 2>&1)
+              exit_code=$?
+
+              # Check if the process exited with a non-zero status
+              if [ $exit_code -ne 0 ]; then
+                  echo "The process exited with a non-zero status: $exit_code"
+                  exit $exit_code
+              fi
+
+              CYPRESS_BASE_URL=$(echo "$output" | grep -o 'Deploy URL: http://[^ ]*' | awk '{print $3}') yarn test:cypress:ci
+
